-- Migration 004: Luhn check digit and client account number generation

-- ============================================================
-- Luhn algorithm implementation in PL/pgSQL
-- Used to compute and validate client account numbers (BSM-######-C)
-- where C is the Luhn check digit over the 6-digit sequence.
-- ============================================================

CREATE SEQUENCE IF NOT EXISTS public.client_sequence START 1 INCREMENT 1;

-- Compute the Luhn check digit for a string of digits.
-- Input: a string of digits (e.g., '000001')
-- Returns: single check digit (0-9) as INTEGER
CREATE OR REPLACE FUNCTION public.luhn_check_digit(digits TEXT)
RETURNS INTEGER
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
  v_sum       INTEGER := 0;
  v_len       INTEGER;
  v_digit     INTEGER;
  v_i         INTEGER;
  v_double    BOOLEAN := TRUE;  -- rightmost digit doubled first in Luhn
BEGIN
  v_len := length(digits);
  FOR v_i IN REVERSE v_len .. 1 LOOP
    v_digit := substring(digits FROM v_i FOR 1)::INTEGER;
    IF v_double THEN
      v_digit := v_digit * 2;
      IF v_digit > 9 THEN
        v_digit := v_digit - 9;
      END IF;
    END IF;
    v_sum := v_sum + v_digit;
    v_double := NOT v_double;
  END LOOP;
  RETURN (10 - (v_sum % 10)) % 10;
END;
$$;

-- Validate a full account number string (digits only, including check digit)
-- Returns TRUE if valid Luhn checksum.
CREATE OR REPLACE FUNCTION public.luhn_valid(full_digits TEXT)
RETURNS BOOLEAN
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
  v_sum       INTEGER := 0;
  v_len       INTEGER;
  v_digit     INTEGER;
  v_i         INTEGER;
  v_double    BOOLEAN := FALSE; -- start from rightmost, not doubling it
BEGIN
  v_len := length(full_digits);
  FOR v_i IN REVERSE v_len .. 1 LOOP
    v_digit := substring(full_digits FROM v_i FOR 1)::INTEGER;
    IF v_double THEN
      v_digit := v_digit * 2;
      IF v_digit > 9 THEN
        v_digit := v_digit - 9;
      END IF;
    END IF;
    v_sum := v_sum + v_digit;
    v_double := NOT v_double;
  END LOOP;
  RETURN (v_sum % 10) = 0;
END;
$$;

-- Generate the next client account number: BSM-######-C
-- Format: BSM-{6-digit zero-padded sequence}-{Luhn check digit}
-- e.g., BSM-000001-8
CREATE OR REPLACE FUNCTION public.generate_client_account_number()
RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
  v_seq       BIGINT;
  v_padded    TEXT;
  v_check     INTEGER;
BEGIN
  v_seq    := nextval('public.client_sequence');
  v_padded := lpad(v_seq::TEXT, 6, '0');
  v_check  := public.luhn_check_digit(v_padded);
  RETURN 'BSM-' || v_padded || '-' || v_check::TEXT;
END;
$$;

-- ============================================================
-- Client status type
-- ============================================================
CREATE TYPE public.client_status AS ENUM (
  'active',
  'inactive',
  'defaulted'
);

-- ============================================================
-- Clients table
-- ============================================================
CREATE TABLE IF NOT EXISTS public.clients (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  account_number          TEXT NOT NULL UNIQUE,   -- BSM-######-C, generated by trigger
  full_name               TEXT NOT NULL,
  phone_number            TEXT NOT NULL,
  national_id             TEXT NOT NULL,
  business_type           TEXT NOT NULL,
  market_location         TEXT NOT NULL,
  daily_business_income   NUMERIC(12,2) NOT NULL CHECK (daily_business_income >= 0),

  -- Guarantor
  guarantor_name          TEXT NOT NULL,
  guarantor_phone         TEXT NOT NULL,
  guarantor_national_id   TEXT NOT NULL,
  guarantor_relationship  TEXT NOT NULL,
  guarantor_business      TEXT NOT NULL,

  status                  public.client_status NOT NULL DEFAULT 'active',
  date_registered         DATE NOT NULL DEFAULT CURRENT_DATE,
  created_by              UUID NOT NULL REFERENCES public.users(id),
  created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Auto-update updated_at
CREATE TRIGGER clients_updated_at
  BEFORE UPDATE ON public.clients
  FOR EACH ROW
  EXECUTE FUNCTION moddatetime(updated_at);

-- Auto-generate account_number on INSERT if not provided
CREATE OR REPLACE FUNCTION public.set_client_account_number()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.account_number IS NULL OR NEW.account_number = '' THEN
    NEW.account_number := public.generate_client_account_number();
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER clients_set_account_number
  BEFORE INSERT ON public.clients
  FOR EACH ROW
  EXECUTE FUNCTION public.set_client_account_number();

-- Prevent account_number from ever being changed after creation
CREATE OR REPLACE FUNCTION public.prevent_account_number_change()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF OLD.account_number <> NEW.account_number THEN
    RAISE EXCEPTION 'account_number is immutable after creation';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER clients_immutable_account_number
  BEFORE UPDATE ON public.clients
  FOR EACH ROW
  EXECUTE FUNCTION public.prevent_account_number_change();

-- Indexes
CREATE INDEX IF NOT EXISTS idx_clients_account_number ON public.clients(account_number);
CREATE INDEX IF NOT EXISTS idx_clients_phone ON public.clients(phone_number);
CREATE INDEX IF NOT EXISTS idx_clients_national_id ON public.clients(national_id);
CREATE INDEX IF NOT EXISTS idx_clients_status ON public.clients(status);
CREATE INDEX IF NOT EXISTS idx_clients_created_by ON public.clients(created_by);

-- Full-text search on name
CREATE INDEX IF NOT EXISTS idx_clients_name_search
  ON public.clients USING gin(to_tsvector('english', full_name));
