-- Migration 005: Groups and group_members

CREATE SEQUENCE IF NOT EXISTS public.group_sequence START 1 INCREMENT 1;

CREATE TYPE public.group_status AS ENUM (
  'active',
  'inactive'
);

-- ============================================================
-- Groups table
-- ============================================================
CREATE TABLE IF NOT EXISTS public.groups (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  group_number TEXT NOT NULL UNIQUE,    -- GRP-###, generated by trigger
  name         TEXT NOT NULL,
  max_members  INTEGER NOT NULL DEFAULT 15 CHECK (max_members > 0 AND max_members <= 15),
  status       public.group_status NOT NULL DEFAULT 'active',
  created_by   UUID NOT NULL REFERENCES public.users(id),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER groups_updated_at
  BEFORE UPDATE ON public.groups
  FOR EACH ROW
  EXECUTE FUNCTION moddatetime(updated_at);

-- Auto-generate GRP-### on INSERT
CREATE OR REPLACE FUNCTION public.set_group_number()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.group_number IS NULL OR NEW.group_number = '' THEN
    NEW.group_number := 'GRP-' || lpad(nextval('public.group_sequence')::TEXT, 3, '0');
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER groups_set_group_number
  BEFORE INSERT ON public.groups
  FOR EACH ROW
  EXECUTE FUNCTION public.set_group_number();

CREATE INDEX IF NOT EXISTS idx_groups_group_number ON public.groups(group_number);
CREATE INDEX IF NOT EXISTS idx_groups_status ON public.groups(status);

-- ============================================================
-- Group members join table
-- ============================================================
CREATE TABLE IF NOT EXISTS public.group_members (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id   UUID NOT NULL REFERENCES public.clients(id),
  group_id    UUID NOT NULL REFERENCES public.groups(id),
  date_joined DATE NOT NULL DEFAULT CURRENT_DATE,
  date_left   DATE,          -- NULL = still active in the group
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT uq_active_member UNIQUE NULLS NOT DISTINCT (client_id, group_id, date_left)
);

CREATE INDEX IF NOT EXISTS idx_group_members_group ON public.group_members(group_id);
CREATE INDEX IF NOT EXISTS idx_group_members_client ON public.group_members(client_id);

-- ============================================================
-- Database-level enforcement of 15-member cap per group.
-- This trigger fires BEFORE INSERT on group_members.
-- It reads max_members from the groups table (which itself
-- is capped at 15 by a CHECK constraint), so the cap is
-- enforced even if the settings table default is changed.
-- ============================================================
CREATE OR REPLACE FUNCTION public.enforce_group_size_limit()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  v_active_count INTEGER;
  v_max_members  INTEGER;
  v_group_name   TEXT;
BEGIN
  -- Count current ACTIVE members (date_left IS NULL)
  SELECT COUNT(*), g.max_members, g.name
  INTO   v_active_count, v_max_members, v_group_name
  FROM   public.group_members gm
  JOIN   public.groups g ON g.id = gm.group_id
  WHERE  gm.group_id = NEW.group_id
    AND  gm.date_left IS NULL
  GROUP BY g.max_members, g.name;

  -- Default to the table's constraint max if group has no members yet
  IF v_max_members IS NULL THEN
    SELECT max_members, name INTO v_max_members, v_group_name
    FROM public.groups WHERE id = NEW.group_id;
  END IF;

  IF COALESCE(v_active_count, 0) >= v_max_members THEN
    RAISE EXCEPTION
      'Group "%" has reached its maximum of % active members.',
      v_group_name, v_max_members
    USING ERRCODE = 'check_violation';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER group_members_enforce_size
  BEFORE INSERT ON public.group_members
  FOR EACH ROW
  EXECUTE FUNCTION public.enforce_group_size_limit();

-- Prevent a client from being in the same group twice simultaneously
-- (the UNIQUE constraint above handles this but we add a clear check)
CREATE OR REPLACE FUNCTION public.prevent_duplicate_active_membership()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM public.group_members
    WHERE client_id = NEW.client_id
      AND group_id  = NEW.group_id
      AND date_left IS NULL
      AND id        <> COALESCE(NEW.id, gen_random_uuid())
  ) THEN
    RAISE EXCEPTION
      'Client is already an active member of this group.'
    USING ERRCODE = 'unique_violation';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER group_members_no_duplicates
  BEFORE INSERT ON public.group_members
  FOR EACH ROW
  EXECUTE FUNCTION public.prevent_duplicate_active_membership();
