-- Migration 006: Loans table and loan number generation

CREATE TYPE public.loan_status AS ENUM (
  'pending',      -- submitted by officer, awaiting approval
  'approved',     -- approved by manager, awaiting disbursement
  'rejected',     -- rejected by manager
  'active',       -- disbursed, repayments in progress
  'closed',       -- all installments paid in full
  'defaulted',    -- flagged as defaulted by daily job
  'refinanced'    -- superseded by a new loan via refinancing netting
);

-- ============================================================
-- Loans table
-- ============================================================
CREATE TABLE IF NOT EXISTS public.loans (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  loan_number          TEXT NOT NULL UNIQUE,        -- generated by trigger: {account_number}-L##
  client_id            UUID NOT NULL REFERENCES public.clients(id),

  -- Amounts (all in GHS)
  principal            NUMERIC(12,2) NOT NULL
                         CHECK (principal >= 1000 AND principal <= 5000),
  fee_amount           NUMERIC(12,2) NOT NULL,      -- = principal * fee_percentage (from settings)
  interest_multiplier  NUMERIC(6,4) NOT NULL,       -- snapshot of settings.interest_multiplier at creation
  total_repayable      NUMERIC(12,2) NOT NULL,      -- = principal * interest_multiplier
  weekly_installment   NUMERIC(12,2) NOT NULL,      -- = total_repayable / term_weeks

  -- Amount actually sent to client (after deductions)
  amount_disbursed_to_client NUMERIC(12,2),         -- set at disbursement

  -- Term
  term_weeks           INTEGER NOT NULL DEFAULT 13,

  -- Workflow
  status               public.loan_status NOT NULL DEFAULT 'pending',
  submitted_by         UUID NOT NULL REFERENCES public.users(id),
  approved_by          UUID REFERENCES public.users(id),
  approval_date        TIMESTAMPTZ,
  rejection_reason     TEXT,                        -- mandatory on rejection
  disbursement_date    DATE,                        -- set when status -> active

  -- Refinancing chain
  previous_loan_id     UUID REFERENCES public.loans(id),  -- nullable, points to old loan

  -- Eligibility flag (advisory, not a hard block)
  declared_weekly_income   NUMERIC(12,2),           -- daily_income * 7, captured at application
  eligibility_ratio        NUMERIC(6,4),            -- weekly_installment / declared_weekly_income
  eligibility_flag         TEXT,                    -- 'eligible' | 'caution' | 'ineligible'

  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Constraints
  CONSTRAINT loans_approval_consistency CHECK (
    (status = 'approved' AND approved_by IS NOT NULL AND approval_date IS NOT NULL) OR
    (status = 'rejected' AND rejection_reason IS NOT NULL) OR
    status IN ('pending', 'active', 'closed', 'defaulted', 'refinanced')
  )
);

CREATE TRIGGER loans_updated_at
  BEFORE UPDATE ON public.loans
  FOR EACH ROW
  EXECUTE FUNCTION moddatetime(updated_at);

-- ============================================================
-- Loan number generation: {client_account_number}-L{##}
-- e.g., BSM-000001-8-L01
-- Sequence per client (tracks all loans including refinanced)
-- ============================================================
CREATE OR REPLACE FUNCTION public.generate_loan_number(p_client_id UUID)
RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
  v_account_number  TEXT;
  v_loan_count      INTEGER;
  v_loan_number     TEXT;
BEGIN
  -- Get the client's account number
  SELECT account_number INTO v_account_number
  FROM public.clients
  WHERE id = p_client_id;

  IF v_account_number IS NULL THEN
    RAISE EXCEPTION 'Client % not found', p_client_id;
  END IF;

  -- Count ALL loans for this client (including rejected, refinanced, etc.)
  -- so the sequence always increments, never reuses
  SELECT COUNT(*) + 1 INTO v_loan_count
  FROM public.loans
  WHERE client_id = p_client_id;

  v_loan_number := v_account_number || '-L' || lpad(v_loan_count::TEXT, 2, '0');
  RETURN v_loan_number;
END;
$$;

CREATE OR REPLACE FUNCTION public.set_loan_number()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.loan_number IS NULL OR NEW.loan_number = '' THEN
    NEW.loan_number := public.generate_loan_number(NEW.client_id);
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER loans_set_loan_number
  BEFORE INSERT ON public.loans
  FOR EACH ROW
  EXECUTE FUNCTION public.set_loan_number();

-- ============================================================
-- Compute loan fields from settings at INSERT time
-- (principal, fee_amount, total_repayable, weekly_installment)
-- These are snapshotted at loan creation — settings changes
-- do NOT retroactively change approved loans.
-- ============================================================
CREATE OR REPLACE FUNCTION public.compute_loan_amounts()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  v_fee_pct     NUMERIC;
  v_multiplier  NUMERIC;
  v_term        INTEGER;
  v_daily_inc   NUMERIC;
  v_weekly_inc  NUMERIC;
  v_ratio       NUMERIC;
  v_threshold   NUMERIC;
BEGIN
  -- Read settings at runtime
  v_fee_pct    := public.get_setting_numeric('fee_percentage');
  v_multiplier := COALESCE(NEW.interest_multiplier, public.get_setting_numeric('interest_multiplier'));
  v_term       := COALESCE(NEW.term_weeks, public.get_setting_int('term_weeks'));

  -- Snapshot settings into the loan row
  NEW.interest_multiplier := v_multiplier;
  NEW.term_weeks          := v_term;
  NEW.fee_amount          := ROUND(NEW.principal * v_fee_pct, 2);
  NEW.total_repayable     := ROUND(NEW.principal * v_multiplier, 2);
  NEW.weekly_installment  := ROUND(NEW.total_repayable / v_term, 2);

  -- Eligibility flag: compare weekly_installment to eligibility_income_ratio * declared_weekly_income
  v_daily_inc := (SELECT daily_business_income FROM public.clients WHERE id = NEW.client_id);
  v_weekly_inc := v_daily_inc * 7;
  NEW.declared_weekly_income := v_weekly_inc;

  IF v_weekly_inc > 0 THEN
    v_ratio     := ROUND(NEW.weekly_installment / v_weekly_inc, 4);
    v_threshold := public.get_setting_numeric('eligibility_income_ratio');
    NEW.eligibility_ratio := v_ratio;

    IF v_ratio <= v_threshold THEN
      NEW.eligibility_flag := 'eligible';
    ELSIF v_ratio <= v_threshold * 1.5 THEN
      NEW.eligibility_flag := 'caution';
    ELSE
      NEW.eligibility_flag := 'ineligible';
    END IF;
  ELSE
    NEW.eligibility_ratio := NULL;
    NEW.eligibility_flag  := 'ineligible';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER loans_compute_amounts
  BEFORE INSERT ON public.loans
  FOR EACH ROW
  EXECUTE FUNCTION public.compute_loan_amounts();

-- ============================================================
-- One active loan per client — enforced at DB level.
-- Checks BEFORE INSERT that the client has no existing
-- active loan. (Refinancing is handled separately in Phase 2.)
-- ============================================================
CREATE OR REPLACE FUNCTION public.enforce_one_active_loan()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM public.loans
    WHERE client_id = NEW.client_id
      AND status = 'active'
  ) THEN
    RAISE EXCEPTION
      'Client already has an active loan. Refinance the existing loan before creating a new one.'
    USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER loans_one_active_per_client
  BEFORE INSERT ON public.loans
  FOR EACH ROW
  WHEN (NEW.status = 'pending')
  EXECUTE FUNCTION public.enforce_one_active_loan();

-- Indexes
CREATE INDEX IF NOT EXISTS idx_loans_client ON public.loans(client_id);
CREATE INDEX IF NOT EXISTS idx_loans_status ON public.loans(status);
CREATE INDEX IF NOT EXISTS idx_loans_submitted_by ON public.loans(submitted_by);
CREATE INDEX IF NOT EXISTS idx_loans_disbursement_date ON public.loans(disbursement_date);
CREATE INDEX IF NOT EXISTS idx_loans_loan_number ON public.loans(loan_number);
